### PR TITLE
#612 Apply Conan Conventions

### PR DESCRIPTION
**Pull request by uilianries**
Related issue: https://github.com/bincrafters/community/issues/612

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries Mac builds failed:
```
Traceback (most recent call last):
  File "/Users/travis/.pyenv/versions/3.7.1/envs/conan/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/Users/travis/.pyenv/versions/3.7.1/envs/conan/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/travis/.pyenv/versions/3.7.1/envs/conan/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
```
please take a look

**Comment by uilianries** [comment]
@SSE4 requests[security] is forcing incompatible pyOpenSSL version. I've submitted a PR to fix it: https://github.com/conan-io/conan/pull/4333

**Comment by SSE4** [comment]
@uilianries is it still not fixed? why does it affect only log4cplus so far (other projects build fine)?

**Comment by uilianries** [comment]
@SSE4 

The problem is when we force to use python 3.7.1 on OSX. You could create a dummy project or re-running an equal project on Travis to get the same error, but the python version on OSX must be 3.7.1

It's not fixed yet, but we could downgrade the version to 3.7.0 or 2.7 for log4cplus for now and update in the future, WDYT?

**Pull request merged**
